const PATTERN_LABELS: Record<string, string> = {
  "NOUN+VERB": "فعل مرکب",
  "VERB+NOUN": "فعل مرکب",
  "NOUN+NOUN": "اسم + اسم",
  "NOUN+ADJ": "اسم + صفت",
  "ADJ+NOUN": "صفت + اسم",
  "ADJ+VERB": "صفت + فعل",
  "VERB+ADJ": "فعل + صفت",
  "ADJ+ADJ": "صفت + صفت",
  "NOUN+PROPN": "اسم + نام خاص",
  "PROPN+NOUN": "نام خاص + اسم",
  "ADJ+PROPN": "صفت + نام خاص",
  "PROPN+ADJ": "نام خاص + صفت",
  "PROPN+PROPN": "نام خاص + نام خاص",
  "PROPN+VERB": "نام خاص + فعل",
  "VERB+PROPN": "نام خاص + فعل",
  "NOUN+ADP": "اسم + حرف اضافه",
  "ADP+NOUN": "حرف اضافه + اسم",
  "ADP+VERB": "حرف اضافه + فعل",
  "VERB+ADP": "فعل + حرف اضافه",
  "ADJ+ADP": "صفت + حرف اضافه",
  "ADP+ADJ": "حرف اضافه + صفت",
  "ADV+NOUN": "قید + اسم",
  "ADV+VERB": "قید + فعل",
  "ADV+ADJ": "قید + صفت",
  "NOUN": "اسم",
  "VERB": "فعل",
  "ADJ": "صفت",
  "ADV": "قید",
  "PROPN": "نام خاص",
};

export function patternLabel(pattern: string): string {
  return PATTERN_LABELS[pattern] ?? pattern;
}
